# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Delete infrastructure with Terraform

on: workflow_dispatch
permissions:
  contents: read

jobs:
  destroy-infa-with-terraform:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Check AWS credentials
        run: |
          aws sts get-caller-identity
          aws s3 ls s3://tf-st-bkt --region ap-south-1

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
       
    # Intialize Terraform
      - name: Terraform Init
        run: terraform init
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}

      # Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
