# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Patient Survival app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build Patient Survival prediction Model
      run: |
        python train_save_model.py

    - name: Save Model to Artifact
      uses: actions/upload-artifact@v3
      with:
        name: patient-survival-model
        path: ./trained_model/xgboost_model.pkl      
  
  provision-with-terraform:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get saved model artifact
        uses: actions/download-artifact@v3
        with:
          name: patient-survival-model
          path: ./trained_model
